/*
 * ============================================================
 *  BASE DE DONNÉES DES HÔTELS
 * ============================================================
 *  ⚠️  Les établissements ci-dessous sont des EXEMPLES FICTIFS
 *  servant à montrer le rendu du site. Remplace-les par de vrais
 *  hôtels avant la mise en ligne (voir README.md).
 *
 *  Champs :
 *   id          identifiant unique, sans espaces ni accents (sert à l'URL)
 *   env         "ville" | "campagne" | "mer" | "montagne"
 *   type        une clé de TYPES (voir plus bas)
 *   price       prix indicatif « à partir de », par nuit, en euros
 *   lat / lng   coordonnées GPS (clic droit sur Google Maps -> copier)
 *   images      URLs des photos (la 1re sert de couverture)
 *   bookingUrl  lien de la fiche Booking.com de l'hôtel
 *               (laisse "" : le site fera une recherche Booking par nom)
 *   partners    liens optionnels vers d'autres sites (expedia, hotelscom, direct)
 *
 *  Champs réservés aux hôtels qui paient une offre (voir plans dans config.js) :
 *   plan        "partenaire" | "premium"  (absent = fiche gratuite)
 *   website     site officiel de l'hôtel (réservation directe)
 *   phone       téléphone affiché sur la fiche
 *   offer       offre spéciale, ex. "-10 % en réservant en direct avec le code NUITS"
 * ============================================================
 */

window.ENVIRONMENTS = {
  ville:    { inLabel: "en ville", label: "Ville",    desc: "Adresses secrètes au cœur des villes",   image: "photo-1502602898657-3e91760cbb34" },
  campagne: { inLabel: "à la campagne", label: "Campagne", desc: "Nature, silence et nuits étoilées",       image: "photo-1500530855697-b586d89ba3ee" },
  mer:      { inLabel: "en bord de mer", label: "Mer",      desc: "Face à l'océan, les pieds dans le sable", image: "photo-1507525428034-b723cf961d3e" },
  montagne: { inLabel: "à la montagne", label: "Montagne", desc: "Refuges d'altitude et chalets perchés",   image: "photo-1464822759023-fed622ff2c3b" },
};

window.TYPES = {
  cabane:     { label: "Cabane perchée",     icon: "🌳" },
  bulle:      { label: "Bulle & dôme",       icon: "🫧" },
  chateau:    { label: "Château",            icon: "🏰" },
  troglodyte: { label: "Troglodyte",         icon: "🪨" },
  phare:      { label: "Phare",              icon: "🗼" },
  igloo:      { label: "Igloo",              icon: "❄️" },
  chalet:     { label: "Chalet d'exception", icon: "🏔️" },
  eau:        { label: "Sur l'eau",          icon: "🛶" },
  yourte:     { label: "Yourte & tipi",      icon: "⛺" },
  historique: { label: "Lieu chargé d'histoire", icon: "🏛️" },
  design:     { label: "Design & art",       icon: "✨" },
  atypique:   { label: "Totalement atypique",icon: "🎩" },
};

const U = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;

window.HOTELS = [
  {
    id: "cabanes-perchees-du-lac",
    name: "Les Cabanes Perchées du Lac",
    tagline: "Dormir à douze mètres du sol, face aux eaux calmes des Landes",
    city: "Biscarrosse", department: "Landes", region: "Nouvelle-Aquitaine",
    env: "campagne", type: "cabane", price: 180, featured: true,
    lat: 44.394, lng: -1.163,
    address: "Route du Lac, 40600 Biscarrosse",
    description: [
      "Nichées dans les pins centenaires qui bordent le lac, ces six cabanes sont accessibles par des passerelles suspendues. Chacune dispose d'une grande baie vitrée ouverte sur l'eau, d'une terrasse privée et d'un bain nordique chauffé au feu de bois.",
      "Le matin, le petit-déjeuner est hissé jusqu'à vous dans un panier en osier. Le soir, on s'endort bercé par le vent dans les branches, à quinze minutes seulement des plages de l'Atlantique.",
    ],
    highlights: ["Bain nordique privatif", "Petit-déjeuner hissé en panier", "Plages océanes à 15 min"],
    amenities: ["Terrasse privée", "Bain nordique", "Petit-déjeuner inclus", "Parking gratuit", "Wi-Fi", "Vélos à disposition"],
    rooms: "6 cabanes pour 2 à 4 personnes",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1449158743715-0a90ebb6d2d8"), U("photo-1441974231531-c6227db76b6e"), U("photo-1476514525535-07fb3b4ae5f1"), U("photo-1618773928121-c32242e63f39")],
    plan: "partenaire", website: "https://www.exemple.fr", phone: "05 58 00 00 03", offer: "-10 % en réservant en direct avec le code NUITS",
    bookingUrl: "", partners: {},
  },
  {
    id: "bulles-d-etoiles-luberon",
    name: "Bulles d'Étoiles",
    tagline: "Une nuit transparente sous le ciel du Luberon",
    city: "Gordes", department: "Vaucluse", region: "Provence-Alpes-Côte d'Azur",
    env: "campagne", type: "bulle", price: 165, featured: true,
    lat: 43.911, lng: 5.200,
    address: "Chemin des Bories, 84220 Gordes",
    description: [
      "Au milieu des champs de lavande et des oliviers, quatre bulles transparentes offrent une vue à 360° sur le ciel provençal. Un télescope et une carte du ciel attendent chaque voyageur.",
      "La journée, profitez de la piscine à débordement face au village perché de Gordes. Le soir, un panier de produits locaux vous est livré pour un dîner sous les étoiles.",
    ],
    highlights: ["Vue à 360° sur les étoiles", "Télescope dans chaque bulle", "Piscine face à Gordes"],
    amenities: ["Piscine", "Climatisation", "Salle de bain privative", "Panier dîner (en option)", "Parking gratuit"],
    rooms: "4 bulles pour 2 personnes",
    checkIn: "17h00", checkOut: "10h30",
    images: [U("photo-1523987355523-c7b5b0dd90a7"), U("photo-1519681393784-d120267933ba"), U("photo-1504280390367-361c6d9f38f4"), U("photo-1500530855697-b586d89ba3ee")],
    plan: "premium", website: "https://www.exemple.fr", phone: "04 90 00 00 01", offer: "Bouteille de rosé du Luberon offerte aux lecteurs de Nuits Singulières",
    bookingUrl: "", partners: {},
  },
  {
    id: "chateau-de-la-brume",
    name: "Château de la Brume",
    tagline: "Vivre en châtelain le temps d'un week-end en Val de Loire",
    city: "Amboise", department: "Indre-et-Loire", region: "Centre-Val de Loire",
    env: "campagne", type: "chateau", price: 290, featured: true,
    lat: 47.413, lng: 0.982,
    address: "Allée des Tilleuls, 37400 Amboise",
    description: [
      "Ce château du XVIe siècle, entouré de douves et d'un parc de vingt hectares, a été restauré avec passion. Les chambres ont conservé cheminées, parquets d'origine et lits à baldaquin.",
      "Dîner aux chandelles dans l'ancienne salle des gardes, balade en montgolfière au-dessus des châteaux de la Loire au lever du soleil : ici, tout invite à ralentir.",
    ],
    highlights: ["Parc de 20 hectares avec douves", "Lits à baldaquin", "Vols en montgolfière au départ du parc"],
    amenities: ["Restaurant gastronomique", "Piscine chauffée", "Spa", "Parking gratuit", "Wi-Fi", "Borne de recharge"],
    rooms: "12 chambres et 2 suites",
    checkIn: "15h00", checkOut: "12h00",
    images: [U("photo-1566073771259-6a8506099945"), U("photo-1590490360182-c33d57733427"), U("photo-1551882547-ff40c63fe5fa"), U("photo-1445019980597-93fa8acb246c")],
    bookingUrl: "", partners: {},
  },
  {
    id: "troglos-de-la-loire",
    name: "Les Troglos de Saumur",
    tagline: "Des suites creusées dans le tuffeau, fraîches et secrètes",
    city: "Saumur", department: "Maine-et-Loire", region: "Pays de la Loire",
    env: "campagne", type: "troglodyte", price: 135,
    lat: 47.260, lng: -0.077,
    address: "Rue des Caves, 49400 Saumur",
    description: [
      "Taillées à même la roche calcaire, ces suites troglodytes gardent une température douce toute l'année. Lumière tamisée, voûtes de pierre blanche et baignoire îlot composent une atmosphère unique.",
      "Au pied des coteaux, découvrez les caves à vin de Saumur-Champigny et les sentiers qui serpentent entre vignes et villages troglodytiques.",
    ],
    highlights: ["Suites creusées dans la roche", "Dégustation de vins en cave", "Baignoire îlot"],
    amenities: ["Petit-déjeuner", "Parking gratuit", "Wi-Fi", "Cave à vin", "Location de vélos"],
    rooms: "5 suites",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1582719478250-c89cae4dc85b"), U("photo-1611892440504-42a792e24d32"), U("photo-1470071459604-3b5ec3a7fe05")],
    bookingUrl: "", partners: {},
  },
  {
    id: "phare-du-bout-du-monde",
    name: "Le Phare du Bout du Monde",
    tagline: "Veiller sur l'océan depuis la chambre du gardien",
    city: "Plouguerneau", department: "Finistère", region: "Bretagne",
    env: "mer", type: "phare", price: 240, featured: true,
    lat: 48.604, lng: -4.505,
    address: "Pointe de la Lande, 29880 Plouguerneau",
    description: [
      "Au sommet d'un ancien phare de la Côte des Légendes, l'unique chambre offre une vue panoramique sur les récifs et les îles. Les nuits de tempête y sont un spectacle inoubliable.",
      "Accessible à marée basse ou en bateau, le phare se mérite. Une expérience rare pour les amoureux de la mer, de la solitude et des grands espaces.",
    ],
    highlights: ["Chambre unique au sommet", "Vue à 360° sur l'océan", "Accès à marée basse"],
    amenities: ["Petit-déjeuner inclus", "Jumelles et cartes marines", "Salle de bain privative", "Parking à terre"],
    rooms: "1 chambre pour 2 personnes",
    checkIn: "Selon marées", checkOut: "Selon marées",
    images: [U("photo-1505142468610-359e7d316be0"), U("photo-1507525428034-b723cf961d3e"), U("photo-1445019980597-93fa8acb246c")],
    bookingUrl: "", partners: {},
  },
  {
    id: "igloo-village-altitude",
    name: "Igloo Village Altitude",
    tagline: "Une nuit dans la glace, à 2 300 mètres",
    city: "Val Thorens", department: "Savoie", region: "Auvergne-Rhône-Alpes",
    env: "montagne", type: "igloo", price: 210,
    lat: 45.298, lng: 6.580,
    address: "Domaine skiable, 73440 Val Thorens",
    description: [
      "Sculptés chaque hiver par des artistes, ces igloos accueillent des chambres aux murs de glace décorés. Duvets grand froid, peaux de mouton et bougies assurent une nuit étonnamment douillette.",
      "La soirée commence par une fondue dans l'igloo-restaurant et se termine dans le jacuzzi extérieur, sous la voie lactée.",
    ],
    highlights: ["Chambres sculptées dans la glace", "Fondue dans l'igloo-restaurant", "Jacuzzi extérieur"],
    amenities: ["Dîner inclus", "Jacuzzi", "Consigne à skis", "Équipement grand froid fourni"],
    rooms: "8 igloos (décembre à avril)",
    checkIn: "18h00", checkOut: "09h00",
    images: [U("photo-1519681393784-d120267933ba"), U("photo-1510798831971-661eb04b3739"), U("photo-1506905925346-21bda4d32df4")],
    bookingUrl: "", partners: {},
  },
  {
    id: "chalet-des-aiguilles",
    name: "Chalet Suspendu des Aiguilles",
    tagline: "Bois, verre et vue frontale sur le Mont-Blanc",
    city: "Chamonix-Mont-Blanc", department: "Haute-Savoie", region: "Auvergne-Rhône-Alpes",
    env: "montagne", type: "chalet", price: 350, featured: true,
    lat: 45.924, lng: 6.869,
    address: "Route des Praz, 74400 Chamonix-Mont-Blanc",
    description: [
      "Architecture contemporaine en porte-à-faux au-dessus de la vallée : chaque suite possède une paroi entièrement vitrée face au massif du Mont-Blanc et un poêle suspendu.",
      "Spa avec piscine intérieure-extérieure, chef privé sur demande et navette vers les remontées mécaniques : le luxe alpin, version design.",
    ],
    highlights: ["Vue frontale sur le Mont-Blanc", "Piscine intérieure-extérieure", "Chef privé sur demande"],
    amenities: ["Spa", "Piscine", "Navette ski", "Restaurant", "Wi-Fi", "Parking couvert"],
    rooms: "7 suites",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1464822759023-fed622ff2c3b"), U("photo-1510798831971-661eb04b3739"), U("photo-1618773928121-c32242e63f39"), U("photo-1493246507139-91e8fad9978e")],
    plan: "premium", website: "https://www.exemple.fr", phone: "04 50 00 00 02", offer: "Accès spa offert pour toute réservation de 2 nuits ou plus",
    bookingUrl: "", partners: {},
  },
  {
    id: "peniche-des-quais",
    name: "La Péniche des Quais",
    tagline: "Se réveiller au fil de la Seine, en plein Paris",
    city: "Paris", department: "Paris", region: "Île-de-France",
    env: "ville", type: "eau", price: 190,
    lat: 48.846, lng: 2.370,
    address: "Port de la Rapée, 75012 Paris",
    description: [
      "Amarrée face à l'île Saint-Louis, cette péniche des années 1930 abrite quatre cabines lambrissées et un pont-terrasse fleuri. Hublots sur la Seine, parquet de teck et literie haut de gamme.",
      "Apéritif au coucher du soleil sur le pont, Notre-Dame à dix minutes à pied : la façon la plus romantique de découvrir Paris.",
    ],
    highlights: ["Pont-terrasse sur la Seine", "Vue sur l'île Saint-Louis", "Notre-Dame à 10 min à pied"],
    amenities: ["Petit-déjeuner", "Climatisation", "Wi-Fi", "Terrasse", "Métro à 3 min"],
    rooms: "4 cabines",
    checkIn: "15h00", checkOut: "11h00",
    images: [U("photo-1499856871958-5b9627545d1a"), U("photo-1502602898657-3e91760cbb34"), U("photo-1611892440504-42a792e24d32")],
    bookingUrl: "", partners: {},
  },
  {
    id: "cabinet-de-curiosites-marais",
    name: "Le Cabinet de Curiosités",
    tagline: "Un hôtel-musée caché dans un hôtel particulier du Marais",
    city: "Paris", department: "Paris", region: "Île-de-France",
    env: "ville", type: "design", price: 260, featured: true,
    lat: 48.857, lng: 2.362,
    address: "Rue des Archives, 75004 Paris",
    description: [
      "Chaque chambre est une pièce de collection : herbiers anciens, globes, papiers peints dessinés à la main et objets chinés. On entre par une porte cochère discrète pour découvrir une cour intérieure végétalisée.",
      "Le bar clandestin du sous-sol sert des cocktails inspirés des voyages des grands explorateurs.",
    ],
    highlights: ["Chambres uniques décorées d'objets chinés", "Bar clandestin", "Cour intérieure végétalisée"],
    amenities: ["Bar", "Petit-déjeuner", "Climatisation", "Wi-Fi", "Conciergerie"],
    rooms: "18 chambres",
    checkIn: "15h00", checkOut: "12h00",
    images: [U("photo-1431274172761-fca41d930114"), U("photo-1590490360182-c33d57733427"), U("photo-1582719478250-c89cae4dc85b")],
    bookingUrl: "", partners: {},
  },
  {
    id: "yourtes-du-vercors",
    name: "Les Yourtes du Vercors",
    tagline: "Nomade d'un soir sur les hauts plateaux",
    city: "Villard-de-Lans", department: "Isère", region: "Auvergne-Rhône-Alpes",
    env: "montagne", type: "yourte", price: 95,
    lat: 45.071, lng: 5.553,
    address: "Plateau des Glovettes, 38250 Villard-de-Lans",
    description: [
      "Cinq yourtes mongoles authentiques, chauffées au poêle à bois, posées sur un plateau d'alpage. Tapis de laine, lits douillets et silence absolu.",
      "Randonnées en raquettes l'hiver, balades à cheval l'été, et une table d'hôtes qui sert les fromages du Vercors.",
    ],
    highlights: ["Yourtes mongoles authentiques", "Table d'hôtes", "Raquettes et balades à cheval"],
    amenities: ["Poêle à bois", "Table d'hôtes", "Sanitaires partagés", "Parking gratuit", "Animaux acceptés"],
    rooms: "5 yourtes pour 2 à 5 personnes",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1504280390367-361c6d9f38f4"), U("photo-1506905925346-21bda4d32df4"), U("photo-1482192596544-9eb780fc7f66")],
    bookingUrl: "", partners: {},
  },
  {
    id: "maison-sur-la-dune",
    name: "La Maison sur la Dune",
    tagline: "Entre le bassin d'Arcachon et l'océan sauvage",
    city: "Lège-Cap-Ferret", department: "Gironde", region: "Nouvelle-Aquitaine",
    env: "mer", type: "design", price: 320, featured: true,
    lat: 44.636, lng: -1.249,
    address: "Allée des Dunes, 33970 Lège-Cap-Ferret",
    description: [
      "Une villa d'architecte en bois brûlé posée sur la dune, avec un accès direct à la plage. Les chambres s'ouvrent sur des terrasses face au coucher de soleil.",
      "Huîtres du bassin au petit-déjeuner, paddle au lever du jour, dîner les pieds dans le sable : l'art de vivre du Cap Ferret.",
    ],
    highlights: ["Accès direct à la plage", "Architecture en bois brûlé", "Couchers de soleil sur l'océan"],
    amenities: ["Accès plage", "Petit-déjeuner", "Paddles et vélos", "Wi-Fi", "Parking"],
    rooms: "6 chambres",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1507525428034-b723cf961d3e"), U("photo-1571896349842-33c89424de2d"), U("photo-1618773928121-c32242e63f39")],
    bookingUrl: "", partners: {},
  },
  {
    id: "moulin-enchante-alsace",
    name: "Le Moulin Enchanté",
    tagline: "Un moulin à eau du XVIIIe siècle au cœur du vignoble alsacien",
    city: "Kaysersberg", department: "Haut-Rhin", region: "Grand Est",
    env: "campagne", type: "atypique", price: 150,
    lat: 48.138, lng: 7.263,
    address: "Rue du Moulin, 68240 Kaysersberg",
    description: [
      "La grande roue tourne toujours sous les fenêtres. Poutres apparentes, meubles peints alsaciens et couettes épaisses : un décor de conte de fées.",
      "À deux pas, les ruelles à colombages de Kaysersberg et la route des vins, idéale à vélo.",
    ],
    highlights: ["Roue à eau en fonctionnement", "Route des vins à vélo", "Village classé à 2 min"],
    amenities: ["Petit-déjeuner", "Wi-Fi", "Parking gratuit", "Salon avec cheminée"],
    rooms: "7 chambres",
    checkIn: "15h00", checkOut: "11h00",
    images: [U("photo-1518780664697-55e3ad937233"), U("photo-1445019980597-93fa8acb246c"), U("photo-1470071459604-3b5ec3a7fe05")],
    bookingUrl: "", partners: {},
  },
  {
    id: "cabane-flottante-dombes",
    name: "Cabanes Flottantes des Dombes",
    tagline: "Au milieu de l'étang, on y accède en barque",
    city: "Villars-les-Dombes", department: "Ain", region: "Auvergne-Rhône-Alpes",
    env: "campagne", type: "eau", price: 140,
    lat: 46.002, lng: 5.030,
    address: "Étang du Grand Birieux, 01330 Villars-les-Dombes",
    description: [
      "Quatre cabanes posées sur l'eau, rejointes en barque à rames. Au réveil, hérons et martins-pêcheurs viennent saluer les voyageurs.",
      "Un paradis pour les amoureux d'oiseaux : le parc ornithologique est à cinq minutes.",
    ],
    highlights: ["Accès en barque", "Observation des oiseaux", "Petit-déjeuner livré en bateau"],
    amenities: ["Petit-déjeuner", "Toilettes sèches", "Parking gratuit", "Gilets de sauvetage"],
    rooms: "4 cabanes pour 2 personnes",
    checkIn: "17h00", checkOut: "10h00",
    images: [U("photo-1439066615861-d1af74d74000"), U("photo-1476514525535-07fb3b4ae5f1"), U("photo-1449158743715-0a90ebb6d2d8")],
    bookingUrl: "", partners: {},
  },
  {
    id: "monastere-blanc-bonifacio",
    name: "Le Monastère Blanc",
    tagline: "Un couvent perché sur les falaises de Bonifacio",
    city: "Bonifacio", department: "Corse-du-Sud", region: "Corse",
    env: "mer", type: "historique", price: 280,
    lat: 41.387, lng: 9.159,
    address: "Haute-Ville, 20169 Bonifacio",
    description: [
      "Les anciennes cellules des moines sont devenues des chambres épurées aux murs de chaux, ouvertes sur la Méditerranée et les côtes sardes.",
      "Le cloître accueille les petits-déjeuners, et la piscine creusée dans la roche surplombe les falaises calcaires.",
    ],
    highlights: ["Vue sur les falaises et la Sardaigne", "Piscine dans la roche", "Cloître du XVe siècle"],
    amenities: ["Piscine", "Petit-déjeuner", "Climatisation", "Wi-Fi", "Restaurant"],
    rooms: "14 chambres",
    checkIn: "15h00", checkOut: "11h00",
    images: [U("photo-1596394516093-501ba68a0ba6"), U("photo-1505142468610-359e7d316be0"), U("photo-1611892440504-42a792e24d32")],
    bookingUrl: "", partners: {},
  },
  {
    id: "tipis-du-larzac",
    name: "Tipis & Étoiles du Larzac",
    tagline: "Le grand ciel des Causses, loin de toute lumière",
    city: "Millau", department: "Aveyron", region: "Occitanie",
    env: "campagne", type: "yourte", price: 85,
    lat: 44.098, lng: 3.078,
    address: "Plateau du Larzac, 12100 Millau",
    description: [
      "Classé réserve de ciel étoilé, le plateau offre l'une des nuits les plus noires de France. Les tipis sont équipés de vrais lits et d'une ouverture pour contempler les étoiles.",
      "Le viaduc de Millau et les gorges du Tarn sont à portée de randonnée.",
    ],
    highlights: ["Réserve de ciel étoilé", "Observation guidée des étoiles", "Gorges du Tarn à proximité"],
    amenities: ["Petit-déjeuner", "Sanitaires partagés", "Parking gratuit", "Animaux acceptés"],
    rooms: "6 tipis",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1504280390367-361c6d9f38f4"), U("photo-1519681393784-d120267933ba"), U("photo-1500530855697-b586d89ba3ee")],
    bookingUrl: "", partners: {},
  },
  {
    id: "toits-de-lyon",
    name: "Hôtel des Toits de Lyon",
    tagline: "Des chambres sous les toits Renaissance du Vieux Lyon",
    city: "Lyon", department: "Rhône", region: "Auvergne-Rhône-Alpes",
    env: "ville", type: "historique", price: 170,
    lat: 45.762, lng: 4.827,
    address: "Rue Saint-Jean, 69005 Lyon",
    description: [
      "Au dernier étage d'une demeure Renaissance, les chambres mansardées offrent une vue sur Fourvière et les toits de tuiles. Traboules secrètes à la sortie de l'hôtel.",
      "Les meilleurs bouchons lyonnais sont au coin de la rue.",
    ],
    highlights: ["Vue sur Fourvière", "Demeure Renaissance classée", "Au cœur du Vieux Lyon"],
    amenities: ["Petit-déjeuner", "Climatisation", "Wi-Fi", "Ascenseur"],
    rooms: "10 chambres",
    checkIn: "14h00", checkOut: "11h00",
    images: [U("photo-1542314831-068cd1dbfeeb"), U("photo-1582719478250-c89cae4dc85b"), U("photo-1590490360182-c33d57733427")],
    plan: "partenaire", website: "https://www.exemple.fr", phone: "04 78 00 00 04",
    bookingUrl: "", partners: {},
  },
  {
    id: "fortin-des-marees",
    name: "Le Fortin des Marées",
    tagline: "Un fort de Vauban cerné par la mer à marée haute",
    city: "Saint-Malo", department: "Ille-et-Vilaine", region: "Bretagne",
    env: "mer", type: "historique", price: 230,
    lat: 48.649, lng: -2.026,
    address: "Grève de Bon-Secours, 35400 Saint-Malo",
    description: [
      "À marée haute, le fort devient une île. Les chambres logent dans les anciennes casemates, entre pierres de granit et larges fenêtres sur la Manche.",
      "Le spectacle des grandes marées, les remparts de la cité corsaire et les huîtres de Cancale font de ce séjour un voyage hors du temps.",
    ],
    highlights: ["Devient une île à marée haute", "Chambres dans les casemates", "Remparts à 5 min"],
    amenities: ["Petit-déjeuner", "Wi-Fi", "Bar", "Parking à terre"],
    rooms: "8 chambres",
    checkIn: "Selon marées", checkOut: "Selon marées",
    images: [U("photo-1505142468610-359e7d316be0"), U("photo-1445019980597-93fa8acb246c"), U("photo-1507525428034-b723cf961d3e")],
    bookingUrl: "", partners: {},
  },
  {
    id: "bulle-nordique-pyrenees",
    name: "Bulle Nordique des Pyrénées",
    tagline: "Le ciel le plus ensoleillé de France, depuis votre lit",
    city: "Font-Romeu", department: "Pyrénées-Orientales", region: "Occitanie",
    env: "montagne", type: "bulle", price: 175,
    lat: 42.505, lng: 2.036,
    address: "Col del Pam, 66120 Font-Romeu",
    description: [
      "À 1 800 mètres, face à la Cerdagne, des dômes chauffés avec jacuzzi privatif. L'air pur et l'ensoleillement exceptionnel en font un refuge toute l'année.",
      "Pistes de ski l'hiver, lacs d'altitude l'été, et le petit train jaune à deux pas.",
    ],
    highlights: ["Jacuzzi privatif", "Vue sur la Cerdagne", "Petit train jaune à proximité"],
    amenities: ["Jacuzzi", "Chauffage", "Petit-déjeuner", "Parking gratuit"],
    rooms: "5 dômes",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1523987355523-c7b5b0dd90a7"), U("photo-1482192596544-9eb780fc7f66"), U("photo-1506905925346-21bda4d32df4")],
    bookingUrl: "", partners: {},
  },
  {
    id: "roulotte-des-vignes",
    name: "La Roulotte des Vignes",
    tagline: "Des roulottes de bohème au milieu des grands crus",
    city: "Beaune", department: "Côte-d'Or", region: "Bourgogne-Franche-Comté",
    env: "campagne", type: "atypique", price: 110,
    lat: 47.025, lng: 4.840,
    address: "Chemin des Climats, 21200 Beaune",
    description: [
      "Roulottes en bois peint, restaurées par un ébéniste, installées au milieu des vignes classées au patrimoine mondial. Chacune possède sa terrasse face au coteau.",
      "Dégustation chez le vigneron du domaine incluse, hospices de Beaune à dix minutes.",
    ],
    highlights: ["Au milieu des Climats de Bourgogne", "Dégustation incluse", "Hospices de Beaune à 10 min"],
    amenities: ["Petit-déjeuner", "Terrasse", "Parking gratuit", "Dégustation"],
    rooms: "5 roulottes",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1500530855697-b586d89ba3ee"), U("photo-1518780664697-55e3ad937233"), U("photo-1611892440504-42a792e24d32")],
    plan: "partenaire", website: "https://www.exemple.fr", phone: "03 80 00 00 05", offer: "Dégustation de 3 grands crus offerte",
    bookingUrl: "", partners: {},
  },
  {
    id: "wagon-lit-riviera",
    name: "Le Wagon-Lit de la Riviera",
    tagline: "L'Orient-Express immobile, face à la Méditerranée",
    city: "Menton", department: "Alpes-Maritimes", region: "Provence-Alpes-Côte d'Azur",
    env: "mer", type: "atypique", price: 200,
    lat: 43.775, lng: 7.497,
    address: "Promenade du Soleil, 06500 Menton",
    description: [
      "D'anciennes voitures-lits des années 1920 transformées en suites Art déco : marqueteries, cuivres et banquettes de velours, à quelques pas des citronniers.",
      "Petit-déjeuner servi dans la voiture-restaurant, plage à deux minutes à pied.",
    ],
    highlights: ["Voitures-lits Art déco", "Voiture-restaurant d'époque", "Plage à 2 min"],
    amenities: ["Petit-déjeuner", "Climatisation", "Wi-Fi", "Bar"],
    rooms: "6 suites",
    checkIn: "15h00", checkOut: "11h00",
    images: [U("photo-1564501049412-61c2a3083791"), U("photo-1590490360182-c33d57733427"), U("photo-1507525428034-b723cf961d3e")],
    bookingUrl: "", partners: {},
  },
  {
    id: "cabane-arbre-sorcier",
    name: "La Cabane de l'Arbre-Sorcier",
    tagline: "Dans la forêt des légendes arthuriennes",
    city: "Paimpont", department: "Ille-et-Vilaine", region: "Bretagne",
    env: "campagne", type: "cabane", price: 150,
    lat: 48.021, lng: -2.172,
    address: "Forêt de Brocéliande, 35380 Paimpont",
    description: [
      "Enroulée autour d'un chêne centenaire, cette cabane a été conçue comme une maison de fée. Escalier en colimaçon, lit rond, et une chasse au trésor pour les enfants.",
      "La fontaine de Barenton et le tombeau de Merlin sont à portée de promenade.",
    ],
    highlights: ["Idéal en famille", "Forêt de Brocéliande", "Chasse au trésor"],
    amenities: ["Petit-déjeuner", "Toilettes sèches", "Parking gratuit"],
    rooms: "3 cabanes pour 2 à 5 personnes",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1441974231531-c6227db76b6e"), U("photo-1449158743715-0a90ebb6d2d8"), U("photo-1470071459604-3b5ec3a7fe05")],
    bookingUrl: "", partners: {},
  },
  {
    id: "cabanon-des-calanques",
    name: "Le Cabanon des Calanques",
    tagline: "Un cabanon de pêcheur au bord de l'eau turquoise",
    city: "Marseille", department: "Bouches-du-Rhône", region: "Provence-Alpes-Côte d'Azur",
    env: "mer", type: "atypique", price: 210,
    lat: 43.210, lng: 5.440,
    address: "Calanque de Sormiou, 13009 Marseille",
    description: [
      "Au cœur du parc national, ce cabanon de pêcheur rénové n'est accessible qu'à pied ou en bateau. Baignade dans une eau cristalline au pied de la terrasse.",
      "Le soir, la calanque se vide et vous appartient.",
    ],
    highlights: ["Au cœur du parc national", "Baignade depuis la terrasse", "Accès à pied ou en bateau"],
    amenities: ["Terrasse", "Kayak", "Cuisine équipée"],
    rooms: "1 cabanon pour 4 personnes",
    checkIn: "16h00", checkOut: "10h00",
    images: [U("photo-1507525428034-b723cf961d3e"), U("photo-1505142468610-359e7d316be0"), U("photo-1596394516093-501ba68a0ba6")],
    bookingUrl: "", partners: {},
  },
  {
    id: "tour-de-guet-carcassonne",
    name: "La Tour de Guet",
    tagline: "Dormir dans les remparts d'une cité médiévale",
    city: "Carcassonne", department: "Aude", region: "Occitanie",
    env: "ville", type: "chateau", price: 185,
    lat: 43.206, lng: 2.364,
    address: "La Cité, 11000 Carcassonne",
    description: [
      "Une tour du XIIIe siècle intégrée aux remparts abrite trois suites sur trois niveaux. Meurtrières transformées en fenêtres, cheminée monumentale et terrasse crénelée.",
      "La nuit, quand les visiteurs sont partis, la Cité s'illumine et devient magique.",
    ],
    highlights: ["Dans les remparts classés UNESCO", "Terrasse crénelée", "Cité illuminée la nuit"],
    amenities: ["Petit-déjeuner", "Climatisation", "Wi-Fi", "Parking réservé"],
    rooms: "3 suites",
    checkIn: "15h00", checkOut: "11h00",
    images: [U("photo-1551882547-ff40c63fe5fa"), U("photo-1590490360182-c33d57733427"), U("photo-1542314831-068cd1dbfeeb")],
    bookingUrl: "", partners: {},
  },
  {
    id: "refuge-de-verre-queyras",
    name: "Le Refuge de Verre",
    tagline: "Le plus haut village d'Europe, dans une cabane de verre",
    city: "Saint-Véran", department: "Hautes-Alpes", region: "Provence-Alpes-Côte d'Azur",
    env: "montagne", type: "design", price: 260,
    lat: 44.701, lng: 6.868,
    address: "Route de la Chapelle, 05350 Saint-Véran",
    description: [
      "Posé à 2 050 mètres dans un mélézin, ce refuge contemporain en verre et mélèze semble flotter au-dessus de la vallée. Sauna panoramique et bibliothèque de montagne.",
      "Le parc naturel du Queyras compte parmi les ciels les plus purs d'Europe : observatoire à proximité.",
    ],
    highlights: ["Sauna panoramique", "Plus haut village d'Europe", "Observatoire à proximité"],
    amenities: ["Sauna", "Demi-pension", "Wi-Fi", "Parking", "Local à skis"],
    rooms: "4 chambres",
    checkIn: "16h00", checkOut: "11h00",
    images: [U("photo-1493246507139-91e8fad9978e"), U("photo-1464822759023-fed622ff2c3b"), U("photo-1618773928121-c32242e63f39")],
    bookingUrl: "", partners: {},
  },
];
